GET http://localhost:5000/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTY1NjQ4MTYzNiwiZXhwIjoxNjU2NDg1MjM2fQ.ONMJacIZECszqfDtODC2rwdTZzfYfBOYggLKJrmZNQc
### 

POST http://localhost:5000/register
Content-Type: application/json

{
  "email": "Mike@bond.com",
  "password": "123456"
}
###

POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "Mike@bond.com",
  "password": "123456"
}