###
GET http://localhost:3000/

###
GET http://localhost:3000/api/pets

###
POST http://localhost:3000/api/pets
Content-Type: application/json

{
    "name" : "Berry",
    "type" : "Bunny",
    "age" : 3
}

###
GET http://localhost:3000/api/pets/sort-age/asc