###
POST http://localhost:3000/register
Content-Type: application/json

{
"email": "user2@gmail.com",
"password": "abcabc"
}


###
POST http://localhost:3000/login
Content-Type: application/json

{
"email": "user2@gmail.com",
"password": "abcabc"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/user-tutorials/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1MzI4MTc4MiwiZXhwIjoxNjUzMjg4OTgyfQ.c96qNOdpFSVJ_Lm-zvzIh_7qoP-2vcHyltstj7pxbhE

###
GET http://localhost:3000/user-tutorials/2


###
GET http://localhost:3000/tutorials
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1MzI4MTc4MiwiZXhwIjoxNjUzMjg4OTgyfQ.c96qNOdpFSVJ_Lm-zvzIh_7qoP-2vcHyltstj7pxbhE




