###
GET http://localhost:3000

###
GET http://localhost:3000/api/shirts

###
POST http://localhost:3000/api/shirts
Content-Type: application/json

{
    "brand": "Reebok",
    "model": "model10",
    "size": "XS",
    "price": 16.99
    
}

###
GET http://localhost:3000/api/shirts/XS