###
GET http://localhost:3000/

###
GET http://localhost:3000/api

###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "email": "vienas@du.lt",
    "password": "trys33"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "vienas@du.lt",
    "password": "trys33"
}